### ISSUE TITLE
Error when submitting CanIHasReview after rebase

### ISSUE THREAD

**Issue by vivekscl** [pyokagan/CanIHasReview#35]
I seem to be getting an error whenever I submit a `CanIHasReview` for this one specific [PR](https://github.com/se-edu/addressbook-level4/pull/844). 

Here's a screenshot of the error I got:
![deepinscreenshot_select-area_20180405211731](https://user-images.githubusercontent.com/17037188/38368069-e8c4e54c-3916-11e8-90dd-a407777b0f1e.png)

And my job ID:
job-9f0302db-31af-4684-9bf4-80ddf400802f

**Comment by Zhiyuan-Amos** [comment]
After working on AB-Level4 for a while, you should write more descriptive issue names uh :P Something like: `Error when submitting CanIHasReview`? :P

**Comment by vivekscl** [comment]
Possible reason:
```
It is possible that CanIHasReview errored because the previous version 
of the PR had an entirely new file added and after rebasing, the file 
now exists in the master branch and hence can't properly get a diff view
```

**Comment by pyokagan** [comment]
@vivekscl 
> It is possible that CanIHasReview errored because the previous version 
> of the PR had an entirely new file added and after rebasing, the file 
> now exists in the master branch and hence can't properly get a diff view

Something like that, but CIHR already properly handles add/add conflicts. In this case, rename detection was messing stuff up and causing a rename/add conflict instead. The solution would thus be to disable rename detection.

Anyway, should be fixed. Open a new issue if it persists.
