### ISSUE TITLE
Internal Server Error bug

### ISSUE THREAD

**Issue by mehak24k** [pyokagan/CanIHasReview#36]
Requesting a review for a PR led to a '500 Internal Server Error'.

The link used was https://canihasreview.pyokagan.com/se-edu/addressbook-level3/pull/67 and the request ID generated is `68290990-3d50-11eb-b6bf-e190add7a22d`.

<img width="1207" alt="Screenshot 2020-12-13 at 10 42 37 PM" src="https://user-images.githubusercontent.com/65491525/102015109-82921d00-3d94-11eb-8117-637e09cbda9f.png">

**Comment by pyokagan** [comment]
Thanks for the bug report! The issue occurred due to an error in CIHR's JSON schema definitions.

The issue has been corrected. It should work now :-)
